package com.david.example.entity;

import java.io.Serializable;

public class FoundationUser implements Serializable {
    /** 用户标识 */
    private String userId;

    /** 用户名 */
    private String userWorkNumber;

    /** 用户工号 */
    private String userName;

    /** 手机号码 */
    private String mobile;

    /** 用户状态 1停用、0活跃 */
    private String userStatus;

    /** 组织名称 */
    private String orgName;

    /** 部门名称 */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foundation_user.user_id
     *
     * @return the value of foundation_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foundation_user.user_id
     *
     * @param userId the value for foundation_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foundation_user.user_work_number
     *
     * @return the value of foundation_user.user_work_number
     *
     * @mbg.generated
     */
    public String getUserWorkNumber() {
        return userWorkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foundation_user.user_work_number
     *
     * @param userWorkNumber the value for foundation_user.user_work_number
     *
     * @mbg.generated
     */
    public void setUserWorkNumber(String userWorkNumber) {
        this.userWorkNumber = userWorkNumber == null ? null : userWorkNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foundation_user.user_name
     *
     * @return the value of foundation_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foundation_user.user_name
     *
     * @param userName the value for foundation_user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foundation_user.mobile
     *
     * @return the value of foundation_user.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foundation_user.mobile
     *
     * @param mobile the value for foundation_user.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foundation_user.user_status
     *
     * @return the value of foundation_user.user_status
     *
     * @mbg.generated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foundation_user.user_status
     *
     * @param userStatus the value for foundation_user.user_status
     *
     * @mbg.generated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foundation_user.org_name
     *
     * @return the value of foundation_user.org_name
     *
     * @mbg.generated
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foundation_user.org_name
     *
     * @param orgName the value for foundation_user.org_name
     *
     * @mbg.generated
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foundation_user.depart_name
     *
     * @return the value of foundation_user.depart_name
     *
     * @mbg.generated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foundation_user.depart_name
     *
     * @param departName the value for foundation_user.depart_name
     *
     * @mbg.generated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        FoundationUser other = (FoundationUser) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserWorkNumber() == null ? other.getUserWorkNumber() == null : this.getUserWorkNumber().equals(other.getUserWorkNumber()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getOrgName() == null ? other.getOrgName() == null : this.getOrgName().equals(other.getOrgName()))
            && (this.getDepartName() == null ? other.getDepartName() == null : this.getDepartName().equals(other.getDepartName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserWorkNumber() == null) ? 0 : getUserWorkNumber().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getOrgName() == null) ? 0 : getOrgName().hashCode());
        result = prime * result + ((getDepartName() == null) ? 0 : getDepartName().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userWorkNumber=").append(userWorkNumber);
        sb.append(", userName=").append(userName);
        sb.append(", mobile=").append(mobile);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", orgName=").append(orgName);
        sb.append(", departName=").append(departName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}