package com.david.example.entity;

import java.io.Serializable;
import java.util.Date;

public class HolidayDutyKey implements Serializable {
    /** 员工号 */
    private String userWorkNumber;

    /** 值班日期 */
    private Date dutyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_duty.user_work_number
     *
     * @return the value of holiday_duty.user_work_number
     *
     * @mbg.generated
     */
    public String getUserWorkNumber() {
        return userWorkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_duty.user_work_number
     *
     * @param userWorkNumber the value for holiday_duty.user_work_number
     *
     * @mbg.generated
     */
    public void setUserWorkNumber(String userWorkNumber) {
        this.userWorkNumber = userWorkNumber == null ? null : userWorkNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column holiday_duty.duty_date
     *
     * @return the value of holiday_duty.duty_date
     *
     * @mbg.generated
     */
    public Date getDutyDate() {
        return dutyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column holiday_duty.duty_date
     *
     * @param dutyDate the value for holiday_duty.duty_date
     *
     * @mbg.generated
     */
    public void setDutyDate(Date dutyDate) {
        this.dutyDate = dutyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HolidayDutyKey other = (HolidayDutyKey) that;
        return (this.getUserWorkNumber() == null ? other.getUserWorkNumber() == null : this.getUserWorkNumber().equals(other.getUserWorkNumber()))
            && (this.getDutyDate() == null ? other.getDutyDate() == null : this.getDutyDate().equals(other.getDutyDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserWorkNumber() == null) ? 0 : getUserWorkNumber().hashCode());
        result = prime * result + ((getDutyDate() == null) ? 0 : getDutyDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userWorkNumber=").append(userWorkNumber);
        sb.append(", dutyDate=").append(dutyDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}