package com.david.example.mapper;

import com.david.example.entity.FoundationUser;
import com.david.example.entity.FoundationUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FoundationUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    long countByExample(FoundationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int deleteByExample(FoundationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int insert(FoundationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int insertSelective(FoundationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    List<FoundationUser> selectByExample(FoundationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    FoundationUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FoundationUser record, @Param("example") FoundationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FoundationUser record, @Param("example") FoundationUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FoundationUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foundation_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FoundationUser record);
}