package com.david.example.mapper;

import com.david.example.entity.HolidayDuty;
import com.david.example.entity.HolidayDutyExample;
import com.david.example.entity.HolidayDutyKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HolidayDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    long countByExample(HolidayDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int deleteByExample(HolidayDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(HolidayDutyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int insert(HolidayDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int insertSelective(HolidayDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    List<HolidayDuty> selectByExample(HolidayDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    HolidayDuty selectByPrimaryKey(HolidayDutyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HolidayDuty record, @Param("example") HolidayDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HolidayDuty record, @Param("example") HolidayDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HolidayDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table holiday_duty
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HolidayDuty record);
}